-- 创建用户表
-- 
CREATE TABLE users (
  id             BIGINT          GENERATED BY DEFAULT AS IDENTITY,

  email          varchar(255)    NOT NULL,
  username       varchar(255)    NOT NULL,
  password_hash  varchar(255)    NOT NULL,
  created_at     TIMESTAMPTZ     NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMPTZ     NOT NULL  DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_username UNIQUE (username)
);