CREATE TABLE notes (
  id         BIGINT         GENERATED BY DEFAULT AS IDENTITY,

  user_id    BIGINT         NOT NULL,
  title      VARCHAR(255)   NOT NULL,
  content    TEXT           NOT NULL,
  created_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_notes PRIMARY KEY (id),
  CONSTRAINT fk_notes_user 
    FOREIGN KEY (user_id) 
      REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_notes_id_user UNIQUE (id, user_id)
);

CREATE INDEX idx_notes_user_id ON notes (user_id);