CREATE TABLE tags (
  id         BIGINT         GENERATED BY DEFAULT AS IDENTITY,

  user_id    BIGINT         NOT NULL,
  name       VARCHAR(255)   NOT NULL,
  color      VARCHAR(255)   NOT NULL,
  created_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tags PRIMARY KEY (id),
  CONSTRAINT fk_tags_user 
    FOREIGN KEY (user_id) 
      REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_tags_user_name UNIQUE (user_id, name),
  CONSTRAINT uq_tags_id_user UNIQUE (id, user_id)
);