spring.application.name=mind-forge

spring.datasource.url=jdbc:postgresql://localhost:5432/mind-forge
spring.datasource.username=MindForge
spring.datasource.password=MindForge
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration